### ISSUE TITLE
Add content to render, like HATEOAS

### ISSUE THREAD

**Issue by lordlele** [evan108108/RESTFullYii#83]
Hi,
what's the best practice to add content to a REST request that was not a model attributes?

Like, for example, hypermedia url ( http://en.wikipedia.org/wiki/HATEOAS ).
My working solutions was this, however I'm not sure if it's really a best practice:

In my model I extend this method:

``` php
    /**
     * Get attributes
     * @param $names mixed
     * @return array of attributes
     */
    public function getAttributes($names = true) {
        $names = parent::getAttributes($names);
        // If application start as REST, this constant was defined
        if (defined("APPLICATION_REST")) {
            $names['url'] = array(
                'myUrl1'  => Yii::app()->createAbsoluteUrl("api/myController/REST.GET", array('someparam' => somevalue)),
                …
            );
        }
        return $names;
    }
```

In this way, if application was in **REST MODE** my model will return an _url_ key with all resource related url (like does github api).

Is this the correct approach?

**Comment by Maykonn** [comment]
The event `model.{{modelname}}.override.attributes` happens when? Before or after the model be save on the database? I'm looking for a way to map request params to the model. For example, suppose that a request has an attribute called `serial` but this attribute must be mapped to the `$modelname->serial_code` attribute.

See: #194

**Comment by evan108108** [comment]
@Maykonn take a look at "model.apply.post.data" and "model.apply.put.data"

**Comment by Maykonn** [comment]
These two events work perfectly, but I don't understand yetthe difference between `pre.filter.model.apply.put.data` and `model.apply.put.data` yet. The same for the http post method.
When one is triggered in relation to the other? 

At the `ERestEventListenerRegistry.php` file we can find the below code:

```PHP
/**
  * model.apply.put.data
  *
  * Called on PUT requests when attempting to apply PUT data
  *
  * @param (Object) (model) the resource model to save data to
  * @param (Array) (data) the data to save to the model
  * @param (Array) (restricted_properties) list of restricted properties
  *
  * @return (Object) the model with PUT data applied
  */
```

But nothing regarding the `ERestEvent::PRE_FILTER_MODEL_APPLY_PUT_DATA` event.

**Comment by evan108108** [comment]
The pre.filter always comes first. Why? Because the pre.filter contains all
of the data the main event closure will use to take an action. Pre.filter
gives you a way of modifying that data without altering the functionality
of the main event closure. The opposite is true for post.filter. This
always comes after the main event closure. You use this to modify the
output / result without overriding the main closure functionality.

So the flow looks like pre.filter -> main event -> post.filter

Please let me know if that makes sense.

Thanks

-evan

**Comment by Maykonn** [comment]
It is clear now to me.

Thank you.
